name: Print and Append Directory Structure to README

on:
  push

jobs:
  print-and-append-directory-structure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Directory Structure
      id: print-directory
      uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@v1.0.2
      with:
        exclude: 'node_modules|.git|.github'
        output-file: 'directory-structure.txt'
    - name: Generate Directory Structure
      id: print-d
      run: |
        # Generate directory structure and save it to a file
        tree -I 'node_modules|.git|.github' -o directory-structure.txt -a
        echo "$(cat directory-structure.txt)"  # Output the captured directory structure
        echo "::set-output name=output-file::directory-structure.txt"

    - name: Append Directory Structure to README
      run: |
        # Get the generated directory structure
        directory_structure=$(cat ${{ steps.print-directory.outputs.output-file }})

        # Print the directory structure for debugging
        echo "Directory Structure:"
        echo "$directory_structure"
        
        # Create a new branch
        git checkout -b add-directory-structure

        # Append it to the README.md file
        echo "## Directory Structure" >> README.md
        echo "```" >> README.md
        echo "$directory_structure" >> README.md
        echo "```" >> README.md

        # Commit the changes
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add README.md
        git commit -m "Append directory structure to README"

        # Push the new branch
        git push origin add-directory-structure
      shell: bash
