name: Print and Append Directory Structure to README

on:
  push

jobs:
  print-and-append-directory-structure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Directory Structure
      id: print-directory
      uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@v1.0.2
      with:
        exclude: 'node_modules|.git|.github'
        output-file: 'directory-structure.txt'
    - name: Generate Directory Structure
      id: print-d
      run: |
        # Generate directory structure and save it to a file
        tree -I 'node_modules|.git|.github' -o directory-structure.txt -a
        echo "Directory Structure: part1"  # Print the directory structure for debugging
        echo "$(cat directory-structure.txt)"  # Output the captured directory structure
        echo "::set-output name=output-file::directory-structure.txt"

    - name: Append Directory Structure to README
      run: |
        # Get the generated directory structure
        directory_structure=$(cat ${{ steps.print-directory.outputs.output-file }})

        # Print the directory structure for debugging
        echo "Directory Structure:"
        echo "$directory_structure"
        
        # Create a new branch with a prefix and a unique identifier
        branch_name="add-directory-structure-${{ github.run_id }}"

        git checkout -b $branch_name

        

        

        # Write Directory_Structure.md file
        echo "## Directory Structure" >> Directory_Structure.md
        echo "```" >> Directory_Structure.md
        cat directory-structure.txt >> Directory_Structure.md
        echo "```" >> Directory_Structure.md

        # Commit the changes
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add README.md
        git add directory-structure.txt
        git commit -m "Append directory structure to README"

        # Push the new branch
        git push origin $branch_name
        
      shell: bash
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Add directory structure to README
        title: Add directory structure to README
        body: |
          This is an automated pull request to add the directory structure to the README.
          It was created by a [GitHub Action](
          https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions).
        branch: add-directory-structure-${{ github.run_id }}
        branch-suffix: timestamp
        base: main
        labels: directory-structure
        reviewers: Devasy23
        assignees: Devasy23
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
