name: Print Directory Structure

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  print-directory-structure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Directory Structure
      uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@v1.0.2
