name: Print Directory Structure

on:
  push:
    branches:
      - main

jobs:
  print-directory-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print directory structure
        uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@v1.0.2

      - name: Update README.md
        uses: github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            const directoryStructure = fs.readFileSync('directory-structure.txt', 'utf8');
            const readmePath = path.join(process.env.GITHUB_WORKSPACE, 'README.md');
            let readmeContent = fs.readFileSync(readmePath, 'utf8');
            const startTag = '<!--START_SECTION:directory_structure-->';
            const endTag = '<!--END_SECTION:directory_structure-->';
            const startTagIndex = readmeContent.indexOf(startTag);
            const endTagIndex = readmeContent.indexOf(endTag);
            if (startTagIndex !== -1 && endTagIndex !== -1) {
              readmeContent = readmeContent.slice(0, startTagIndex + startTag.length) + '\n```\n' + directoryStructure + '\n```\n' + readmeContent.slice(endTagIndex);
              fs.writeFileSync(readmePath, readmeContent);
            }
