- name: Print directory structure
  # You may pin to the exact commit or the version.
  # uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@553df9b35280b89f01b0f3e4d93d9171095a55d4
  uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@v1.0.2
